steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:0.12.20'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
          cd scripts  
          env=${scripts/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* Present directory: ${env} ********"
          echo "*************************************************"
          terraform init 
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.20'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
          cd scripts  
          env=${scripts}
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* Present directory: ${env} ********"
          echo "*************************************************"
          terraform plan 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.12.20'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
          cd scripts  
          env=${scripts}
          echo ""
          echo "*************** TERRAFOM APPLY ******************"
          echo "******* Present directory: ${env} ********"
          echo "*************************************************"
          terraform apply -auto-approve
      
# [END tf-apply]      
