steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:0.12.20'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
        terraform init
        done
      
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.20'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      terraform plan 
      done
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.12.20'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      terraform apply -auto-approve
# [END tf-apply]      
